# Generated by Django 3.2.25 on 2025-12-11 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=50, verbose_name='Adresse Ligne 1')),
                ('address_line_2', models.CharField(blank=True, max_length=50, verbose_name='Adresse Ligne 2 (Optionnel)')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='Ville')),
                ('state', models.CharField(blank=True, max_length=50, verbose_name='État/Province')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Pays')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='users/profile_pics/', verbose_name='Photo de Profil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
        ),
    ]
