# Generated by Django 3.2.25 on 2025-12-11 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la Categorie')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, unique=True, verbose_name='Nom du Produit')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Description Détaillée')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (MGA)')),
                ('images', models.ImageField(upload_to='photos/products', verbose_name='Image Principale')),
                ('stock', models.IntegerField(verbose_name='Quantité en Stock')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible à la vente')),
                ('reorder_point', models.IntegerField(default=5, verbose_name='Seuil Critique de Commande')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Dernière Modification')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ('-created_date',),
            },
        ),
    ]
