# Generated by Django 3.2.25 on 2025-12-12 09:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewandrating_reviewimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewandrating',
            name='rating',
            field=models.IntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Note (sur 7 étoiles)'),
        ),
    ]
