# Generated by Django 5.2.9 on 2025-12-30 06:31

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_reviewandrating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[800, 800], upload_to='photos/products', verbose_name='Image Principale'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=None, size=[800, 800], upload_to='photos/product_gallery', verbose_name='Image Additionnelle'),
        ),
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=70, scale=None, size=[600, 600], upload_to='photos/reviews/%Y/%m/%d/', verbose_name='Image jointe'),
        ),
    ]
