# Generated by Django 3.2.25 on 2026-03-05 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_images_alter_productimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_size',
            field=models.BooleanField(default=False, verbose_name='Gestion des tailles'),
        ),
    ]
