# Generated by Django 3.2.25 on 2025-11-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('story', models.TextField()),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='about_banners/')),
                ('photo_image', models.ImageField(blank=True, null=True, upload_to='about_photos/')),
            ],
            options={
                'verbose_name_plural': 'Information de la Boutique',
            },
        ),
    ]
