# Generated by Django 3.2.25 on 2025-12-11 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_1',
            field=models.CharField(default='-', max_length=50, verbose_name='Adresse Ligne 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Adresse Ligne 2 (Optionnel)'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart_id_at_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='-', max_length=50, verbose_name='Ville'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=models.CharField(default='-', max_length=50, verbose_name='Pays'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='-', max_length=50, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='-', max_length=50, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Numéro de Commande'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Total Commande'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='-', max_length=15, verbose_name='Téléphone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(default='-', max_length=50, verbose_name='État/Province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'Nouvelle'), ('Accepted', 'Acceptée'), ('Completed', 'Terminée'), ('Cancelled', 'Annulée')], default='New', max_length=10, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Taxes'),
        ),
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Dernière Mise à Jour'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de Création'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Payée'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire payé')),
                ('variant', models.CharField(blank=True, max_length=100, verbose_name='Variante')),
                ('is_ordered', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Commande')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Article de Commande',
                'verbose_name_plural': 'Articles de Commande',
            },
        ),
    ]
